# Generated by Django 4.2.2 on 2023-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='original')),
                ('processed', models.ImageField(upload_to='processed')),
                ('created_at', models.DateTimeField(verbose_name='Created published')),
            ],
        ),
    ]
